export class Timeline {
  projectVersions = [
    {
      Authors: null,
      BD: null,
      BusinessVertical: 'MedCom',
      CMLevel1: { results: Array(2) },
      CMLevel2: { LookupId: 286, LookupValue: 'Rahul Chamle', Email: 'rahul.chamle@cactusglobal.com' },
      ClientLegalEntity: 'Test_KB',
      CommentsMT: null,
      ConferenceJournal: null,
      DeliveryLevel1: { results: Array(1) },
      DeliveryLevel2: { LookupId: 287, LookupValue: 'Maxwell Fargose', Email: 'maxwell.fargose@cactusglobal.com' },
      DescriptionMT: null,
      Editor: { LookupId: 222, LookupValue: 'Arvind Kushwaha', Email: 'arvind.kushwaha@cactusglobal.com' },
      ID: 73,
      Indication: null,
      IsCurrentVersion: true,
      IsPubSupport: 'No',
      Milestone: 'Draft 1',
      Modified: '2020-09-07T07:27:10Z',
      Molecule: 'Abatacept',
      PrimaryPOC: 30,
      PriorityST: 'High-complexity',
      ProjectCode: 'KBT00-ABS-200044',
      ProjectFolder: '/sites/medcomdev/TestKB/KBT00-ABS-200044',
      ProjectType: 'Deliverable-Writing',
      ProposedEndDate: '2020-10-06T18:30:00Z',
      ProposedStartDate: '2020-09-08T18:30:00Z',
      PubSupportStatus: null,
      SOWBoxLink: null,
      SOWCode: 'TSTKB-SOW',
      SOWLink: null,
      Status: 'Author Review',
      TA: 'Cross Product',
      Title: 'Prj_Title',
      VersionId: 5632,
      VersionLabel: '11.0',
      WBJID: 'Prj_Title',
      __metadata: { id: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion3d1dce01-97b6-4574-936d-d46bb4d9ccbd', uri: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion3d1dce01-97b6-4574-936d-d46bb4d9ccbd', type: 'SP.ListItemVersion' },
      __proto__: Object
    },
    {
      Authors: null,
      BD: null,
      BusinessVertical: 'MedCom',
      CMLevel1: { results: Array(2) },
      CMLevel2: { LookupId: 286, LookupValue: 'Rahul Chamle', Email: 'rahul.chamle@cactusglobal.com' },
      ClientLegalEntity: 'Test_KB',
      CommentsMT: null,
      ConferenceJournal: null,
      DeliveryLevel1: { results: Array(2) },
      DeliveryLevel2: { LookupId: 287, LookupValue: 'Maxwell Fargose', Email: 'maxwell.fargose@cactusglobal.com' },
      DescriptionMT: null,
      Editor: { LookupId: 79, LookupValue: 'Kaushal Bagrodia', Email: 'kaushal.bagrodia@cactusglobal.com' },
      ID: 73,
      Indication: null,
      IsCurrentVersion: false,
      IsPubSupport: 'No',
      Milestone: 'Draft 1',
      Modified: '2020-09-02T09:40:41Z',
      Molecule: 'Abatacept',
      PrimaryPOC: 30,
      PriorityST: 'High-complexity',
      ProjectCode: 'KBT00-ABS-200044',
      ProjectFolder: '/sites/medcomdev/TestKB/KBT00-ABS-200044',
      ProjectType: 'Deliverable-Writing',
      ProposedEndDate: '2020-10-06T18:30:00Z',
      ProposedStartDate: '2020-09-08T18:30:00Z',
      PubSupportStatus: null,
      SOWBoxLink: null,
      SOWCode: 'TSTKB-SOW',
      SOWLink: null,
      Status: 'Author Review',
      TA: 'Cross Product',
      Title: 'Prj_Title',
      VersionId: 5120,
      VersionLabel: '10.0',
      WBJID: 'Prj_Title',
      __metadata: { id: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion34b0962f-f70b-49cc-8286-7e3ccc90f36b', uri: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion34b0962f-f70b-49cc-8286-7e3ccc90f36b', type: 'SP.ListItemVersion' },
      __proto__: Object
    },
    {
      Authors: null,
      BD: null,
      BusinessVertical: 'MedCom',
      CMLevel1: { results: Array(2) },
      CMLevel2: { LookupId: 286, LookupValue: 'Rahul Chamle', Email: 'rahul.chamle@cactusglobal.com' },
      ClientLegalEntity: 'Test_KB',
      CommentsMT: null,
      ConferenceJournal: null,
      DeliveryLevel1: { results: Array(2) },
      DeliveryLevel2: { LookupId: 287, LookupValue: 'Maxwell Fargose', Email: 'maxwell.fargose@cactusglobal.com' },
      DescriptionMT: null,
      Editor: { LookupId: 79, LookupValue: 'Kaushal Bagrodia', Email: 'kaushal.bagrodia@cactusglobal.com' },
      ID: 73,
      Indication: null,
      IsCurrentVersion: false,
      IsPubSupport: 'No',
      Milestone: 'Draft 1',
      Modified: '2020-09-02T09:39:20Z',
      Molecule: 'Abatacept',
      PrimaryPOC: 30,
      PriorityST: 'High-complexity',
      ProjectCode: 'KBT00-ABS-200044',
      ProjectFolder: '/sites/medcomdev/TestKB/KBT00-ABS-200044',
      ProjectType: 'Deliverable-Writing',
      ProposedEndDate: '2020-10-06T18:30:00Z',
      ProposedStartDate: '2020-09-08T18:30:00Z',
      PubSupportStatus: null,
      SOWBoxLink: null,
      SOWCode: 'TSTKB-SOW',
      SOWLink: null,
      Status: 'Author Review',
      TA: 'Cross Product',
      Title: 'Prj_Title',
      VersionId: 4608,
      VersionLabel: '9.0',
      WBJID: 'Prj_Title',
      __metadata: { id: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion27a4ea95-836e-4171-a1b8-20f03f101747', uri: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion27a4ea95-836e-4171-a1b8-20f03f101747', type: 'SP.ListItemVersion' },
      __proto__: Object
    }, {
      Authors: null,
      BD: null,
      BusinessVertical: 'MedCom',
      CMLevel1: { results: Array(2) },
      CMLevel2: { LookupId: 286, LookupValue: 'Rahul Chamle', Email: 'rahul.chamle@cactusglobal.com' },
      ClientLegalEntity: 'Test_KB',
      CommentsMT: null,
      ConferenceJournal: null,
      DeliveryLevel1: { results: Array(2) },
      DeliveryLevel2: { LookupId: 287, LookupValue: 'Maxwell Fargose', Email: 'maxwell.fargose@cactusglobal.com' },
      DescriptionMT: null,
      Editor: { LookupId: 79, LookupValue: 'Kaushal Bagrodia', Email: 'kaushal.bagrodia@cactusglobal.com' },
      ID: 73,
      Indication: null,
      IsCurrentVersion: false,
      IsPubSupport: 'No',
      Milestone: 'Draft 1',
      Modified: '2020-09-02T09:19:57Z',
      Molecule: 'Abatacept',
      PrimaryPOC: 30,
      PriorityST: 'High-complexity',
      ProjectCode: 'KBT00-ABS-200044',
      ProjectFolder: '/sites/medcomdev/TestKB/KBT00-ABS-200044',
      ProjectType: 'Deliverable-Writing',
      ProposedEndDate: '2020-10-06T18:30:00Z',
      ProposedStartDate: '2020-09-08T18:30:00Z',
      PubSupportStatus: null,
      SOWBoxLink: null,
      SOWCode: 'TSTKB-SOW',
      SOWLink: null,
      Status: 'Author Review',
      TA: 'Cross Product',
      Title: 'Prj_Title',
      VersionId: 4096,
      VersionLabel: '8.0',
      WBJID: 'Prj_Title',
      __metadata: { id: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion3809fbc3-b5a2-4924-a3c4-4c3230d43c83', uri: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion3809fbc3-b5a2-4924-a3c4-4c3230d43c83', type: 'SP.ListItemVersion' },
      __proto__: Object
    }, {
      Authors: null,
      BD: null,
      BusinessVertical: 'MedCom',
      CMLevel1: { results: Array(2) },
      CMLevel2: { LookupId: 286, LookupValue: 'Rahul Chamle', Email: 'rahul.chamle@cactusglobal.com' },
      ClientLegalEntity: 'Test_KB',
      CommentsMT: null,
      ConferenceJournal: null,
      DeliveryLevel1: { results: Array(2) },
      DeliveryLevel2: { LookupId: 287, LookupValue: 'Maxwell Fargose', Email: 'maxwell.fargose@cactusglobal.com' },
      DescriptionMT: null,
      Editor: { LookupId: 79, LookupValue: 'Kaushal Bagrodia', Email: 'kaushal.bagrodia@cactusglobal.com' },
      ID: 73,
      Indication: null,
      IsCurrentVersion: false,
      IsPubSupport: 'No',
      Milestone: 'Draft 1',
      Modified: '2020-09-02T09:17:38Z',
      Molecule: 'Abatacept',
      PrimaryPOC: 30,
      PriorityST: 'High-complexity',
      ProjectCode: 'KBT00-ABS-200044',
      ProjectFolder: '/sites/medcomdev/TestKB/KBT00-ABS-200044',
      ProjectType: 'Deliverable-Writing',
      ProposedEndDate: '2020-10-06T18:30:00Z',
      ProposedStartDate: '2020-09-08T18:30:00Z',
      PubSupportStatus: null,
      SOWBoxLink: null,
      SOWCode: 'TSTKB-SOW',
      SOWLink: null,
      Status: 'Author Review',
      TA: 'Cross Product',
      Title: 'Prj_Title',
      VersionId: 3584,
      VersionLabel: '7.0',
      WBJID: 'Prj_Title',
      __metadata: { id: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersionbe39ef1d-cf30-4a52-b2b3-3653019250e5', uri: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersionbe39ef1d-cf30-4a52-b2b3-3653019250e5', type: 'SP.ListItemVersion' },
      __proto__: Object
    }, {
      Authors: null,
      BD: null,
      BusinessVertical: 'MedCom',
      CMLevel1: { results: Array(2) },
      CMLevel2: { LookupId: 286, LookupValue: 'Rahul Chamle', Email: 'rahul.chamle@cactusglobal.com' },
      ClientLegalEntity: 'Test_KB',
      CommentsMT: null,
      ConferenceJournal: null,
      DeliveryLevel1: { results: Array(2) },
      DeliveryLevel2: { LookupId: 287, LookupValue: 'Maxwell Fargose', Email: 'maxwell.fargose@cactusglobal.com' },
      DescriptionMT: null,
      Editor: { LookupId: 79, LookupValue: 'Kaushal Bagrodia', Email: 'kaushal.bagrodia@cactusglobal.com' },
      ID: 73,
      Indication: null,
      IsCurrentVersion: false,
      IsPubSupport: 'No',
      Milestone: 'Draft 1',
      Modified: '2020-09-02T09:11:32Z',
      Molecule: 'Abatacept',
      PrimaryPOC: 30,
      PriorityST: 'High-complexity',
      ProjectCode: 'KBT00-ABS-200044',
      ProjectFolder: '/sites/medcomdev/TestKB/KBT00-ABS-200044',
      ProjectType: 'Deliverable-Writing',
      ProposedEndDate: '2020-10-06T18:30:00Z',
      ProposedStartDate: '2020-09-08T18:30:00Z',
      PubSupportStatus: null,
      SOWBoxLink: null,
      SOWCode: 'TSTKB-SOW',
      SOWLink: null,
      Status: 'In Progress',
      TA: 'Cross Product',
      Title: 'Prj_Title',
      VersionId: 3072,
      VersionLabel: '6.0',
      WBJID: 'Prj_Title',
      __metadata: { id: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion0b1ffe6e-cc12-4f08-b02d-abbfe3bddb7a', uri: 'https://cactusglobal.sharepoint.com/sites/medcomde…stItemVersion0b1ffe6e-cc12-4f08-b02d-abbfe3bddb7a', type: 'SP.ListItemVersion' },
      __proto__: Object
    }
  ];

  timelineObj = {
    ID: 73,
    counter: 0,
    data: [],
    entityType: 'ProjectMgmt_ProjectInformationCT',
    moduleName: '',
    propertiesRequired: ['Title', 'ProjectType', 'PubSupportStatus', 'DescriptionMT', 'ConferenceJournal', 'SOWCode', 'Authors', 'CommentsMT', 'BusinessVertical', 'PrimaryPOC', 'TA', 'Indication', 'Molecule', 'PriorityST', 'Status', 'IsPubSupport', 'SOWBoxLink', 'SOWLink', 'BD', 'CMLevel1', 'CMLevel2', 'DeliveryLevel1', 'DeliveryLevel2', 'WBJID', 'Milestone', 'ProposedStartDate', 'ProposedEndDate'],
    status: 'Pending',
    verDifference: [],
    versionUrl: { select: 'Id,ProjectType, DescriptionMT,ClientLegalEntity, P…Id, Modified, Editor/LookupId, Editor/LookupValue', Expand: 'CMLevel1, CMLevel2, DeliveryLevel1, DeliveryLevel2, Editor, BD', skip: '{{skipCount}}', top: '{{top}}' },
    versions: [],
  };
}
